### ISSUE TITLE
Cluster Dendrogram shows only 9 characters for nominal variable names

### ISSUE THREAD

**Issue by ShugoSUWAZONO** [hyunsooseol/snowCluster#10]
I would love to have at least 10 characters..
![スクリーンショット 2022-06-27 9 56 05](https://user-images.githubusercontent.com/62045540/175841745-e4bdcdf8-7e8b-4849-8920-665b85136af1.png)

**Comment by hyunsooseol** [comment]
Dear ShugoSUWAZONO

Oh I see. I will add option to handle this soon. 
Cheers
Seol

**Comment by ShugoSUWAZONO** [comment]
Dear hyunsooseol,
Thanks a lot for this quick response. I look forward to seeing the improvement!
