### ISSUE TITLE
settings for Hierarchical Clustering Dendrogram

### ISSUE THREAD

**Issue by coledavis** [hyunsooseol/snowCluster#11]
Hi. I assume that the Hierarchical Clustering Dendogram is to be used as an attractive and convenient version of hierarchical clustering, whereas the Hierarchical clustering method gives a choice of settings.   Can I assume that the Hierarchical Clustering Dendogram runs along the default settings of the other tool, i.e. standardized data, Euclidean distance and Ward D2 clustering? 

I'm currently working on the second editions of my statistics books using jamovi, including a chapter on cluster analysis, so I would be grateful for your help with this.

Cole

**Comment by hyunsooseol** [comment]
Hi coledavis
I implemented additional options as you suggested shown below. It will be available tommorrow in the jamovi library.

With thanks
Seol
![이미지 1](https://user-images.githubusercontent.com/37318620/179776310-554c54eb-80d8-46c3-83ae-0e7ea3ceee83.png)

**Comment by coledavis** [comment]
Thank you. That was unexpected, but I really look forward to it.    I guess I wanted to know if there was a reason for the two different tools.  Or are they just two ways of looking at the same thing?

**Comment by hyunsooseol** [comment]
@coledavis 

At first, I made it because I wanted a slightly better clustering dendrogram picture. The analysis in HCD module is done using `factoextra::hcut` R function and `factoextra:: fviz_dend` R function.

You will find useful information in `factoextra` R package.

With thanks
Seol

**Comment by coledavis** [comment]
Thank you, Seol, much appreciated. I look forward to seeing the new changes.  Best wishes.   Cole

**Comment by hyunsooseol** [comment]
@coledavis 
You can update it now shown below.

Cheers
Seol

![image](https://user-images.githubusercontent.com/37318620/179906811-c167d8f6-a83c-41a2-87e2-61ebb57a88e2.png)
