### ISSUE TITLE
Discriminant Analysis

### ISSUE THREAD

**Issue by Hernaniafc** [hyunsooseol/snowCluster#12]
Cant plot results of - [ ] @ #> [**Diacriminant**](url) Analysis

![image](https://user-images.githubusercontent.com/82900162/185808698-098f33e0-3b96-4984-b729-c52157ca79f5.png)

**Comment by hyunsooseol** [comment]
Hi [Hernaniafc](https://github.com/Hernaniafc)

Could you click all the options to see what happens? or send me an omv file that produces error.

Cheers
Seol
