### ISSUE TITLE
More cluster centers than distinct data points using Snow Cluster add-in to Jamovi

### ISSUE THREAD

**Issue by swahull** [hyunsooseol/snowCluster#17]
I am experiencing a problem with Snow Cluster K-means clustering using Jamovi. My Jamovi dataset has 5800+ records, each with 5 variables to base the clusters on.  There are 2 issues, firstly that optimal number of clusters always seems to be 1, which makes no sense given the diversity of data. The main issue is that I get the error "more cluster centers than distinct data points" whenever the number of clusters selected exceeds the number of variables entered (5), so it works fine selecting 2, 3, 4, 5 clusters, but if I enter 6 for the number of clusters, I immediately get this error. I get the same error using a smaller data set of 50 records.  Working out clustering in Excel, I come up with 10 clusters. Please advice on what might be causing this problem so I can fix it. Source data is available if requested.  I have seen remarks on this error relating to programming in r, but I am not writing or adjusting the code, just using Jamovi to drive the Snow Clustering.  I am running on an iMac Pro M4 with 64GB memory, Mac Monterey OS, with Jamovi 2.3.28 (latest stable).  I can provide the data if needed.

**Comment by hyunsooseol** [comment]
Hi 

The error message is not relate jamovi but R codes.
I am using `stats::kmeans` R package to perform kmeans in jamovi.

Best
Seol

**Comment by swahull** [comment]
@hyunsooseol is that a separate plug in module, sorry for my ignorance, not really gotten into R yet, perhaps I should.  Jamovi seemed the ideal front end to R, but looks like I might have to jump into R.  Would you be willing to expand on your response about stats::kmeans ? (where do I get it, how to use it etc.)

**Comment by hyunsooseol** [comment]
Hi

The "``stat`s`" package in R is a core package that provides a wide range of statistical functions and methods for data analysis. you can search` kmeans` function using google search.

Best
Seol
