### ISSUE TITLE
snowCluster::caret does not work in ubuntu system

### ISSUE THREAD

**Issue by zhaohongxin0** [hyunsooseol/snowCluster#18]
Hi , 
The machine learning part of the package, snowCluster::caret can run well in R (windows).
However, in R (ubuntu), or in Rstudio (cloud version), we got no results (empty tables or figures). 
How can we run it in a Linux evironment?
Thanks
James

**Comment by hyunsooseol** [comment]
Hi James

I can't test this because I don't use Linux.
 If you want to know more about this, ask in the forums on jamovi.org.
 
 Best
 Seol
