### ISSUE TITLE
Problems with the extension snowCluster package

### ISSUE THREAD

**Issue by gonzalezdurruthy** [hyunsooseol/snowCluster#19]
Hello Professor Hyunsooseol

I have the version jamovi-2.4.8.0-win64 installed and I would like to use the snowCluster package. However, it is not available and I get an error message. I have thought about installing the most recent version jamovi-2.4.11.0-win64. Could you confirm if this could solve the installation and operation problem of the snowCluster extension with this new version?

Please, you can alternatively replay to gonzalezdurruthy.furg@gmail.com

Many thanks in advances

Michael

**Comment by hyunsooseol** [comment]
Hi [gonzalezdurruthy](https://github.com/gonzalezdurruthy)

yes, you should install the latest version(current version) in your computer and the issue will be resolved I think.

Best Regards
Seol
