### ISSUE TITLE
Saving cluster membership as nominal

### ISSUE THREAD

**Issue by pa0** [hyunsooseol/snowCluster#2]
Thank you for the package! It makes my life so much easier :-)
When saving a cluster membership, is it possible to specify that the new variable should be of type Nominal, not Continuous? A variable of type Continous cannot be used to split in exploratory analysis.

**Comment by hyunsooseol** [comment]
You can copy a cluster membership column clicking mouse button and just paste it to the next column.
Cheers
Seol

**Comment by pa0** [comment]
Thank You for this solution. The better way is to prepare transformation with the nominal variable as an effect, but both ways are making the database a little messy, and require extra effort. 
Of course, if setting the level of cluster membership isn't possible then close this issue, but I hope You can improve this :-)

**Comment by hyunsooseol** [comment]
I fixed it right before. Would you update snowCluster module in the jamovi library tomorrow?

Cheers
Seol

**Comment by jose-andres79** [comment]
Thanks a lot for this module. I have been looking for the possibility of multidimensional analysis in Jamovi for a long time. Do you plan to include non-metric MDS in future versions?

**Comment by lillemets** [comment]
I have a related issue. For the life of me, I can not figure out how to save the cluster as a new variable in data. I can not find any checkboxes that would allow me to do this (as with some other procedures). I'm using the latest version of Jamovi and snowCluster.

**Comment by hyunsooseol** [comment]
Hi lillemets

If you are trying to run hierarchical clustering method, You will find "cluster option" in the hierarchical dendrogram shown below[
![이미지 1](https://user-images.githubusercontent.com/37318620/119564257-8b772800-bde3-11eb-9572-fcf7c9db86e5.png)

**Comment by lillemets** [comment]
I'm not sure how could I have missed that. It's there and also so for the K-means method. However, the "Hierarchical clustering method" does not have this option. I think it would also make sense to add it there.

**Comment by hyunsooseol** [comment]
Hi lillemets

It produces the same results for "Hierarchical clustering method".
