### ISSUE TITLE
error message: "more clusters than distinct data points"

### ISSUE THREAD

**Issue by cmarani8** [hyunsooseol/snowCluster#20]
Hi there,

Thank you in advance for your help on this issue. I am not the strongest statistician, so I hope this question makes sense. 

I am attempting to run a k-means cluster analysis using the snowCluster module in JAMOVI. All of my variables are continuous, and it's only when I add some of the variables to the analysis that this error pops up. I am trying to run a cluster analysis with 3 clusters. I am not sure how to fix this. Any help is appreciated!

**Comment by hyunsooseol** [comment]
Hi [cmarani8](https://github.com/cmarani8)

Could you attach a file or sample that causes error here? I will check it.

Best
Seol

**Comment by hyunsooseol** [comment]
Hi [cmarani8](https://github.com/cmarani8)

it is working with 3 clusters for all variables entered. I attach omv file.
[GSS2018_CSM2023rev.zip](https://github.com/hyunsooseol/snowCluster/files/13329426/GSS2018_CSM2023rev.zip)
Best
Seol
