### ISSUE TITLE
Request for a Guide for Jamovi SnowCluster

### ISSUE THREAD

**Issue by WeiJieLim468** [hyunsooseol/snowCluster#21]
Hi Prof Hyunsoo, I am new to machine learning. May I know if you have a guide or glossary for your SnowCluster package? I have researched the technical short forms such as "svmlinear" and "rf" using Google. It will be enormously helpful if you have a resource to advise me on how to use your SnowCluster package. Let me know if you have a resource somewhere. Thank you very much in advance.

**Comment by hyunsooseol** [comment]
Hi [WeiJieLim468](https://github.com/WeiJieLim468)

Thank you for using snowCluster module.

The snowCluster module was developed based on the `caret` R package. In machine learning analysis, the training model can be referred to the abbreviation of the `caret` package. The `caret` package is shown in the figure below, click the link  in program.

![image](https://github.com/hyunsooseol/snowCluster/assets/37318620/5ab68263-4b3b-4488-a662-72ac640a7cb1)

Kind Regards
Seol

**Comment by WeiJieLim468** [comment]
Hi Prof Hyunsoo, thank you for your prompt reply. I will check out the caret package. Thank you.
