### ISSUE TITLE
교수님 안녕하세요, 군집분석 관련하여 여쭙고자 합니다. 

### ISSUE THREAD

**Issue by woongbear** [hyunsooseol/snowCluster#26]
![스크린샷 2024-05-29 오후 6 04 46](https://github.com/hyunsooseol/snowCluster/assets/171135270/d99799d6-e77a-4dea-9da9-363b4ce5b062)

사진에서와 같이 Centroids of clusters Table와 plot of means across clusters 군집 평균이 반대로 제시되는데 제가 해석을 잘못한 것일까요?

감사합니다!

**Comment by hyunsooseol** [comment]
안녕하세요. 
먼저 jamovi 와 snowCluster  모듈이 최신 버전인지 확인하세요. 아니라면 최신버전으로 업데이트 하시기 바랍니다.
그리고 예제 파일을 한번 돌려보세요. iris 파일 가지고 해보았는데 정상적으로 출력 되고 있습니다.
![image](https://github.com/hyunsooseol/snowCluster/assets/37318620/f327a1e2-de19-42f8-abea-4e5cffebcdd1)

**Comment by woongbear** [comment]
교수님, 감사합니다! 업데이트하니 결과가 제대로 나옵니다! 고맙습니다~

**Comment by hyunsooseol** [comment]
감사합니다.  제가 확인해보니  R 코드도 동일한 반복을 하니 군집1 과 군집 2가 가끔 바뀌는데 plot은 안바뀌고 있는 문제를 발견했습니다. 그래서 버그 수정을 했습니다. 
아마도 다음주 초경에  snowCluster 모듈을 업데이트 하시면 됩니다. 다시한번 발견되지 못한 버그를 지적해주셔서 감사 합니다. ^^ 오늘도 좋은 저녁 되세요~

**Comment by woongbear** [comment]
감사합니다. 덕분에 통계프로그램 잘 쓰고 있습니다!

**Comment by hyunsooseol** [comment]
지금  jamovi library에서 업데이트 하시면 됩니다. 사용해보시고 문제가 있으면 연락을 주세요. 감사합니다.
![image](https://github.com/hyunsooseol/snowCluster/assets/37318620/0d7bf9dd-aad3-485d-b6f6-71efffeec14b)
