### ISSUE TITLE
Save k-means clusters in data

### ISSUE THREAD

**Issue by GianvitoL** [hyunsooseol/snowCluster#27]
Hello,
I would like to make a request: currently, using the module "Multidimensional scaling plot", it is not possible to save the k-means clusters into the dataset as an actual variable.
I would like to have this possibility, if possible.

Thanks a lot!

**Comment by hyunsooseol** [comment]
Hi [GianvitoL](https://github.com/GianvitoL)

Thanks for your request. I will update it in the next version.

Best Regards
Seol

**Comment by hyunsooseol** [comment]
Hi [GianvitoL](https://github.com/GianvitoL)

You can update it in jamovi library now.
![image](https://github.com/hyunsooseol/snowCluster/assets/37318620/dc35bfb7-7de7-495c-bbc4-baa98312c479)

Best Regards
Seol

**Comment by GianvitoL** [comment]
Dear hyunsooseol,
Thanks a lot for the extremely quick update! I am impressed!
I just checked out the new module version: this is exactly what I needed!

Thanks again for your amazing work!

All my best wishes

Gianvito
