### ISSUE TITLE
Feature request: centroids on LD plot in discriminant analysis?

### ISSUE THREAD

**Issue by Me-eyes** [hyunsooseol/snowCluster#29]
Dear Hyunsoo,
I've just tried out the linear discriminant part of your snowCluster module and I'm loving it! Easy to use and a very elegant output. However, I was wondering if it would be possible to request an option that adds in the group centroids (the mean discriminant scores) on the LD plot?
Cheers,
Paul

**Comment by hyunsooseol** [comment]
Hi Paul
Thanks for your suggestions.
I will let you know if it's possible.

Kind Regards
Seol

**Comment by Me-eyes** [comment]
Dear Seol,
That looks perfect! Thank you so much for looking at this so soon :)

Best wishes,
Paul

**Comment by hyunsooseol** [comment]
Thanks for your suggestion again.

It will be updated on next Monday. I will let you know on board.

Cheers
Seol

**Comment by hyunsooseol** [comment]
Hi

Update it in jamovi library now.
![image](https://github.com/user-attachments/assets/7cbed0e2-871e-4c99-a1c0-bad7f089b1de)

Cheers
Seol
