### ISSUE TITLE
non-metric MDS

### ISSUE THREAD

**Issue by jose-andres79** [hyunsooseol/snowCluster#3]
Thanks a lot for this module. I have been looking for the possibility of multidimensional analysis in Jamovi for a long time. Do you plan to include non-metric MDS in future versions?

**Comment by hyunsooseol** [comment]
Sorry, I don't have a plan to implement non-metric MDS  in the near future.

**Comment by jose-andres79** [comment]
Okay. No problem. Thank you very much again.
