### ISSUE TITLE
Doubt about K-mean analysis

### ISSUE THREAD

**Issue by celiagconejo** [hyunsooseol/snowCluster#30]
Hello, 
First of all, thanks for the snowCluster package. 
I have tried to do a K-mean analysis to make 2 clusters with a single variable (in my case, the number of meters run in a test). The k-means option allows to do it with at least 3 variables. Would it be possible to do it with only 1 to establish the cut-off point of 2 clusters?

I look forward to hearing from you
Best regards 
Celia

**Comment by hyunsooseol** [comment]
Hi Celia
