### ISSUE TITLE
K-means clustering does not work for k >= 3

### ISSUE THREAD

**Issue by cristinagarciamata** [hyunsooseol/snowCluster#31]
K-means clustering works as usual when the number of clusters is set to 2 (k=2), but as soon as I try to change the k to a higher number, the analysis does not run (see picture). I have tried it on various other devices, but the module keeps getting stuck (and I know it worked like two weeks ago). 

![Capture04](https://github.com/user-attachments/assets/4e465113-47c4-4c88-b74e-56cf3516d9c8)

**Comment by hyunsooseol** [comment]
Hi [cristinagarciamata](https://github.com/cristinagarciamata)

Could you attach .omv file that produces error in here?

Kind Regards
Seol

**Comment by cristinagarciamata** [comment]
Hi Seol,

here is the .omv files with the error. Thanks for your quick reply!
I had to change the name of the file ending to .omv.txt because GitHub did not let me attach .omv files. 

Kind regards
Cristina


[KMeans_Problem.omv.txt](https://github.com/user-attachments/files/17005408/KMeans_Problem.omv.txt)

**Comment by hyunsooseol** [comment]
Hi [cristinagarciamata](https://github.com/cristinagarciamata)

Oh. You should attach the file as **zip** file here cause I can not open txt file.

Kind Regards
Seol

**Comment by cristinagarciamata** [comment]
Hi @hyunsooseol 

thanks for the hint. Here is the attached file as zip:
[KMeans_Problem.omv.zip](https://github.com/user-attachments/files/17005495/KMeans_Problem.omv.zip)

Kind Regards
Cristina

**Comment by hyunsooseol** [comment]
Hi
Here is a example of zip file that you shoud attach in here.

sample.zip

**Comment by hyunsooseol** [comment]
Hi [cristinagarciamata](https://github.com/cristinagarciamata)

This is not an error of module. In general, the number of variables should be greater than the number of clusters.

Kind Regards
Seol

**Comment by cristinagarciamata** [comment]
Oh, thanks for the clarification! 

As one of the plots recommended k=5 for my data, I thought it might be possible to calculate it.
