### ISSUE TITLE
ROC analysis snowCluster module

### ISSUE THREAD

**Issue by celiagconejo** [hyunsooseol/snowCluster#32]
Hello,
Thank you very much for the snowCluster module. The ROC analysis does not work for me because the classification variable says " <text>:1:2:unexpected symbol 1: 6MWT_300 ^. I have checked that there are no gaps in the variables, but it still does not work for me. I would like to have the graphics available.
Best Regards
Celia

**Comment by hyunsooseol** [comment]
Hi [celiagconejo](https://github.com/celiagconejo)

Could you attach .omv file as zip in here or email me at snow@cau.ac.kr

Kind Regards
Seol

**Comment by hyunsooseol** [comment]
email me at [snow@cau.ac.kr](mailto:snow@cau.ac.kr)
