### ISSUE TITLE
Error: Duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by DavidEllingsonEddington** [hyunsooseol/snowCluster#4]
In my data the rows aren't named,so having duplicates is impossible. I get this when using the analyses in snowCluster such as Hierachrical Clustering and PCA plot. My data are attached. When "County" is the label variable this error doesn't occur, but when other Labels such as "3Regions" is selected, the error pops up.
[WEKA data.csv](https://github.com/hyunsooseol/snowCluster/files/6600201/WEKA.data.csv)

**Comment by hyunsooseol** [comment]
Hi
As you can shown below, The name of levels is duplicated. for example, 'Central' is appeared 8 times in the data. In this case, the error message is appeared.

Cheers
Seol

![이미지 2](https://user-images.githubusercontent.com/37318620/120881283-e80beb80-c60a-11eb-821c-1fc26a08ea62.png)

**Comment by jonathon-love** [comment]
hi seol,

it would be nice if you could produce a nice error message which explains what the problem is ... 

cheers
