### ISSUE TITLE
Discriminant analysis SnowCluster

### ISSUE THREAD

**Issue by estr2525** [hyunsooseol/snowCluster#9]
The plots will not work (just spin forever) is this a jamovi update issue?

**Comment by hyunsooseol** [comment]
Hi estr2525

Could you share  .omv file to check it out?
With thanks
Seol

**Comment by estr2525** [comment]
Of course Dr. Seol! Thank you I’m attaching it. I labeled the problems. The dichotomous one works but the plots just “spin” and the polytomous one only “spins.” I am using a Mac and my jamovi version is 1.6.23.0. Thank you again!

**Comment by hyunsooseol** [comment]
Hi estr2525

I can not find your attached file. otherwise, send me an email at snow@cau.ac.kr
and you can use the newest version of jamovi(2.3.2) and see if what happens.

With thanks
Seol

**Comment by hyunsooseol** [comment]
Hi estr2525

When I take a look at your DA.omv. It seems that module is not a module I developed.  Here is a DA screen that I developed as shown below and it works well.
![image](https://user-images.githubusercontent.com/37318620/160260051-abd89049-864a-4059-87cf-94de302bafa0.png)

**Comment by hyunsooseol** [comment]
Hi estr2525

![image](https://user-images.githubusercontent.com/37318620/160260120-4e5a32f3-99ca-433f-9db3-c614bc226bb2.png)

this module that you are trying to run now.

With thanks
Seol

**Comment by estr2525** [comment]
Hi! I only edited the title of the analysis, its definitely snowCluster I used. Could you send me the jamovi file with the graphs,  I wonder if it’s just my computer not having enough memory. My screen shot without editing the title of the Results section:

**Comment by hyunsooseol** [comment]
Hi you can update jamovi 2.3.2 and the newest version of snowCluster module in jamovi library, and unzip the attached file below;
[DA.zip](https://github.com/hyunsooseol/snowCluster/files/8358586/DA.zip)
